.PHONY: test lint fuzz vuln build

# awssecrets is a separate module, so ./... from here does not reach it.
test:
	go test -race ./...
	cd awssecrets && go test -race ./...

lint:
	go vet ./...
	staticcheck ./...
	cd awssecrets && go vet ./...
	cd awssecrets && staticcheck ./...

fuzz:
	go test -fuzz=FuzzHelloFrame -fuzztime=60s .

vuln:
	govulncheck ./...
	cd awssecrets && govulncheck ./...

build:
	go build -o bin/gocloak ./cmd/gocloak
	go build -o bin/gocloak-sink ./cmd/gocloak-sink
	go build -o bin/gocloak-send ./cmd/gocloak-send
